# Addition of compiler GCC for C/C++
CC = gcc

# Addition of compilation flags for debugging and warning deactivation
CFLAGS = -g -Wall

# Taget executable
TARGET = main

# Code compilation
all: $(TARGET)

$(TARGET): $(TARGET)
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c	

clean:
	$(RM) $(TARGET)
